"""initial_schema_with_indexes

Revision ID: 1c2639285902
Revises: 
Create Date: 2026-09-21 01:02:53.616457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2639285902'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('called_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_index('ix_appointments_date_service_slot', ['appointment_date', 'service_id', 'time_slot'], unique=False)
        batch_op.create_index('ix_appointments_date_status', ['appointment_date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_scheduled_start'), ['scheduled_start'], unique=False)
        batch_op.create_index('ix_appointments_student_date', ['student_id', 'appointment_date', 'service_id'], unique=False)

    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.create_index('ix_appeals_student_status', ['student_id', 'status'], unique=False)
        batch_op.create_index('ix_appeals_staff_status', ['assigned_staff_id', 'status'], unique=False)
        batch_op.create_index('ix_appeals_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_appeals_service_id', ['service_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_audit_logs_user_id', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id'), ['telegram_chat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id'))
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_student_date')
        batch_op.drop_index(batch_op.f('ix_appointments_scheduled_start'))
        batch_op.drop_index('ix_appointments_date_status')
        batch_op.drop_index('ix_appointments_date_service_slot')
        batch_op.alter_column('called_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))

    # ### end Alembic commands ###
